from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class AIArticleAnalysis(BaseModel):
    """Response from AI when analyzing an article"""
    is_relevant: bool
    exam_type: Literal["citizenship", "pr", "both"] | None = None
    topic: str | None = None
    summary: str | None = None
    questions: list["AIGeneratedQuestion"] | None = None


class AIGeneratedQuestion(BaseModel):
    """Single question generated by AI"""
    stem: str
    choice_a: str
    choice_b: str
    choice_c: str
    correct_choice: Literal["a", "b", "c"]
    explanation: str
    difficulty: Literal["easy", "medium", "hard"]
    exam_type: Literal["citizenship", "pr", "both"]
    topic: str
    learning_objective: str | None = None


class Article(BaseModel):
    """Current affairs article"""
    id: UUID
    title: str
    url: str
    source: str
    published_date: datetime | None
    summary: str | None
    exam_type: str | None
    topic: str | None
    is_relevant: bool
    processing_status: str
    created_at: datetime


class Question(BaseModel):
    """Current affairs question"""
    id: UUID
    article_id: UUID
    question_stem: str
    choice_a: str
    choice_b: str
    choice_c: str
    correct_choice: Literal["a", "b", "c"]
    explanation: str
    difficulty: str
    exam_type: str
    topic: str | None
    learning_objective: str | None = None
    quality_score: float = 0
    expires_at: datetime
    created_at: datetime


class PracticeRequest(BaseModel):
    """Request to start a current affairs practice session"""
    exam_type: Literal["citizenship", "pr", "both"] = "both"
    difficulty: Literal["easy", "medium", "hard"] | None = None
    count: int = Field(default=10, ge=1, le=20)
    exclude_question_ids: list[UUID] = Field(default_factory=list, max_length=1000)
    refresh_articles: bool = True
    article_count: int = Field(default=6, ge=1, le=10)


class PracticeQuestion(BaseModel):
    """Question for practice session"""
    id: UUID
    question_stem: str
    choice_a: str
    choice_b: str
    choice_c: str
    topic: str | None
    difficulty: str
    article_title: str
    article_url: str


class AnswerSubmission(BaseModel):
    """User's answer submission"""
    question_id: UUID
    user_choice: Literal["a", "b", "c"]


class AnswerResult(BaseModel):
    """Result after submitting an answer"""
    is_correct: bool
    correct_choice: Literal["a", "b", "c"]
    explanation: str

